# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' my_fun Title
#'
#' @return 1
#' @export
#'
#' @examples
#' my_fun()
my_fun <- function() {
  if (requireNamespace("cranology", quietly = TRUE)) {
    cranology::cran_packages_history
  } else {
    "no cranology"
  }
}
